
server:
  port: 3000


#datasource
spring:
  thymeleaf:
    cache: false

#    mysql
#  datasource:
#    name: blog
#    url: jdbc:mysql://localhost:3306/blog
#    username: root
#    password: root
#     # 使用数据源
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver


# h2
  datasource:
#    url: jdbc:h2:file:~/h2/blog;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    url: jdbc:h2:file:~/h2/blog;AUTO_SERVER=TRUE
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true




  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true



#logging
logging:
  level:
    root: DEBUG
