#测试环境配置
server:
  port: 3000


#datasource
spring:
  thymeleaf:
    cache: false



# h2
  datasource:
    url: jdbc:h2:mem:blog;DB_CLOSE_DELAY=-1
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true




  jpa:
    generate-ddl: true
    properties:
      hibernate.format_sql: true



#logging
logging:
  level:
    root: info
